### PR TITLE
Renaming of Events and a bit more javadoc

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc we could do this in a different PR, though...

However, I want to land the `AGPUSH-1413-clustering-apns-service-holder` on UPS upstream master first.

How far away from merging is that PR against upstream ?

**Comment by matzew** [comment]
@lfryc speaking of JavaDoc, I noticed there is zero javadoc on `MetricCollectionTrigger` and the `CdiJmsBridge` class lacks JavaDoc as well. Can you add some ?

**Comment by matzew** [comment]
@lfryc any comments ?

**Comment by lfryc** [comment]
@matzew nope, this perfectly make sense, sorry I missed this PR...

**Comment by lfryc** [comment]
Thanks @matzew , merged here: https://github.com/aerogear/aerogear-unifiedpush-server/pull/696

**Pull request merged**
